kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cronjob-reader
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
metadata:
  name: cronjob-reader-pod
subjects:
- kind: ServiceAccount
  namespace: default
  name: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cronjob-reader
  apiGroup: ""