service-ingress-hpa:
  deployment:
    enabled: false
    type: "deployment"
  minReplicas: 2
  maxReplicas: 20
  namespace: 'default'
  env:
    NODE_CONFIG_ENV: staging
    NODE_ENV: production
  rolloutNotifications:
    slack: argo-cd-test